version: "3"
services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    env_file:
      - ./common.env
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: 
      - insnet
  postgres:
    build: ./postgres
    container_name: postgres
    env_file:
      - ./common.env
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - insnet
  redash-data:
    build: ./redash/data
    container_name: redash-data
    env_file:
      - ./common.env
    environment:
      - LC_ALL=C.UTF-8
    volumes:
      - rddata:/var/lib/postgresql/data
    networks: 
      - insnet

  kibana:
    build: ./kibana
    container_name: kibana
    depends_on:
      - elasticsearch
      - postgres
    env_file:
      - ./common.env
    ports: 
      - 5601:5601
    networks: 
      - insnet
  grafana:
    build: ./grafana
    container_name: grafana
    depends_on:
      - elasticsearch
      - postgres
    env_file:
      - ./common.env
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    ports: 
      - 3000:3000
    networks: 
      - insnet
  metabase:
    build: ./metabase
    container_name: metabase
    depends_on:
      - elasticsearch
      - postgres
    env_file:
      - ./common.env
    ports: 
      - 3001:3000
    networks: 
      - insnet
  redash-server:
    build: ./redash/server
    container_name: redash-server
    command: server
    depends_on:
      - elasticsearch
      - postgres
      - redash-data
      - redash-redis
    ports:
      - "5000:5000"
    env_file:
      - ./common.env
      - ./redash/redash-connection.env
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_WEB_WORKERS: 4
    networks: 
      - insnet
  redash-worker:
    build: ./redash/worker
    container_name: redash-worker
    command: scheduler
    depends_on:
      - elasticsearch
      - postgres
      - redash-data
      - redash-redis
    env_file:
      - ./common.env
      - ./redash/redash-connection.env
    environment:
      PYTHONUNBUFFERED: 0
      WORKERS_COUNT: 1
      QUEUES: "queries,scheduled_queries,celery"
    networks: 
      - insnet
  redash-front:
    build: ./redash/front
    container_name: redash-front
    depends_on:
      - elasticsearch
      - postgres
      - redash-server
    ports:
      - "8081:80"
    env_file:
      - ./common.env
      - ./redash/redash-connection.env
    links:
      - redash-server:redash
    networks: 
      - insnet
  redash-redis:
    build: ./redash/redis
    container_name: redash-redis
    depends_on:
      - elasticsearch
      - postgres
    env_file:
      - ./common.env
    networks: 
      - insnet

volumes:
  esdata:
    driver: local
  pgdata:
    driver: local
  rddata:
    driver: local

networks:
  insnet: