apiVersion: v1
kind: ConfigMap
metadata:
  name: db-envoy-config
data:
  envoy.yaml: |-
    admin:
      access_log_path: /dev/stdout
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 9901
    static_resources:
      listeners:
        - name: db.listener
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 8000
          filter_chains:
            - filters:
              - name: db.listener.proxy
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.network.redis_proxy.v3.RedisProxy
                  stat_prefix: db.listener.proxy.redis
                  prefix_routes:
                    routes:
                      - cluster: redis.cluster
                  settings:
                    op_timeout: 1s
      clusters:
        - name: redis.cluster
          connect_timeout: 0.25s
          type: strict_dns
          lb_policy: round_robin
          hosts:
            - socket_address:
                address: 127.0.0.1
                port_value: 6379