apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      layer: db-node
  template:
    metadata:
      name: db-pod
      labels:
        layer: db-node
    spec:
      containers:
        - name: db-mesh
          image: envoyproxy/envoy:v1.16.0
          ports:
            - name: db-port
              containerPort: 8000
          args:
            - "--config-path /etc/envoy/envoy.yaml"
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy/envoy.yaml
              subPath: envoy.yaml
        - name: db-container
          image: redis:5.0.9
          ports:
            - containerPort: 6379
      volumes:
        - name: envoy-config
          configMap:
            name: db-envoy-config
            items:
              - key: envoy.yaml
                path: envoy.yaml