apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.yaml: |-
    spring:
      redis:
        host: redis-service
      zipkin:
        baseUrl: http://published-tracing-service:9411/
        service:
          name: app-service
