apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      layer: app-node
  template:
    metadata:
      name: app-pod
      labels:
        layer: app-node
    spec:
      containers:
        - name: app-container
          image: localhost:5000/glory_of/k8s-tracing-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: "app-config"
            - name: CUSTOM_TRACE_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CUSTOM_TRACE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CUSTOM_TRACE_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUSTOM_TRACE_PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP