---
apiVersion: v1
kind: Service
metadata:
  name: published-service
spec:
  type: LoadBalancer
  selector:
    layer: web-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: published-tracing-service
spec:
  type: LoadBalancer
  selector:
    layer: tracing-node
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
