apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-store-db
  labels:
    app: event-store-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-store-db
  template:
    metadata:
      labels:
        app: event-store-db
    spec:
      containers:
        - name: event-store-db
          image: eventstore/eventstore:24.6.0-alpha-arm64v8
          ports:
            - name: app-port
              containerPort: 2113
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: "All"
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
            - name: EVENTSTORE_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"
          volumeMounts:
            - mountPath: "/var/lib/eventstore"
              name: event-store-data-volume
      volumes:
        - name: event-store-data-volume
          emptyDir: {}