apiVersion: v1
kind: Service
metadata:
  name: event-store-db
spec:
  type: NodePort
  selector:
    app: event-store-db
  ports:
    - name: app-outer-port
      protocol: TCP
      port: 2113
      targetPort: app-port
      nodePort: 30113