apiVersion: v1
kind: Service
metadata:
  # Kibanaのデフォルトの接続先がhttp://elasticsearch:9200なので
  # そこにつながるように設定するためこの名前にしている
  name: elasticsearch
spec:
  selector:
    layer: es-node
  ports:
    - protocol: TCP
      name: port-9200
      port: 9200
      targetPort: 9200
    - protocol: TCP
      name: port-9300
      port: 9300
      targetPort: 9300