spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/monitor-db
    username: monitor-user
    password: monitor-pass
    maximum-pool-size: 90
    auto-commit: false
    connection-timeout: 300000
