apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  type: NodePort
  selector:
    app: zipkin
  ports:
    - name: zipkin-outer-port
      protocol: TCP
      port: 9411
      targetPort: zipkin-port
      nodePort: 30411