apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      layer: app-pod
  template:
    metadata:
      name: app-pod
      labels:
        layer: app-pod
    spec:
      containers:
        - name: app-container
          image: localhost:5000/glory_of/monitor-jvm-practice-app
          imagePullPolicy: Never
          ports:
            - name: app-port
              containerPort: 8080
          env:
            - name: "SERVER_TOMCAT_THREADS_MAX"
              value: "50"
          resources:
            limits:
              memory: "256Mi"
          command:
            - "java"
            - "-Xmx50M"
            - "-Xss512k"
            - "-XX:MaxMetaspaceSize=55M"
            - "-XX:ReservedCodeCacheSize=15M"
            - "-XX:CompressedClassSpaceSize=7M"
            - "-XX:MaxDirectMemorySize=2M"
            - "-jar"
            - "/app.jar"
