spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/local-database
    username: local-user
    password: local-password
    maximum-pool-size: 90
    auto-commit: false
    connection-timeout: 300000
config:
  value:
    local environment!