apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  type: LoadBalancer
  selector:
    layer: db-node
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379