apiVersion: v1
kind: Service
metadata:
  name: app-outer-service
spec:
  type: NodePort
  selector:
    app: practice-app
  ports:
    - name: app-outer-port
      protocol: TCP
      port: 8080
      targetPort: app-port
      nodePort: 30080
    - name: metrics-outer-port
      protocol: TCP
      port: 8888
      targetPort: metrics-port
      nodePort: 30888