version: "3"
services:
  db1:
    build: ./db
    container_name: db1
    volumes:
      - ./conf/mongod.conf:/etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_DATABASE: replica-db
    env_file:
      - ./common.env
    ports:
      - 27017:27017
    networks: 
      - dbnet
    command: mongod --config /etc/mongo/mongod.conf
  db2:
    build: ./db
    container_name: db2
    volumes:
      - ./conf/mongod.conf:/etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_DATABASE: replica-db
    env_file:
      - ./common.env
    ports:
      - 27018:27017
    networks: 
      - dbnet
    command: mongod --config /etc/mongo/mongod.conf
  db3:
    build: ./db
    container_name: db3
    volumes:
      - ./conf/mongod.conf:/etc/mongo/mongod.conf
    environment:
      MONGO_INITDB_DATABASE: replica-db
    env_file:
      - ./common.env
    ports:
      - 27019:27017
    networks: 
      - dbnet
    command: mongod --config /etc/mongo/mongod.conf
volumes:
  dbdata:
    driver: local
networks:
  dbnet: