apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    layer: db-data-node
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: sentinel
      protocol: TCP
      port: 26379
      targetPort: 26379