{
 "title": "[DBLog]DBログダッシュボード",
 "time": { "from": "2015-05-16T15:00:00.000Z", "to": "2015-05-21T03:00:00.000Z" },
 "panels": [
  {
   "title": "[DBLog]一時間ごとのアクセス",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(access_at,1h,0),\n  count(id) AS \"id\"\nFROM access_logs\nWHERE\n  $__timeFilter(access_at)\nGROUP BY 1\nORDER BY 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[DBLog:ブラウザごとのアクセス",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  1 AS \"time\",\n  browser AS metric,\n  count(browser)\nFROM access_logs\nWHERE\n  $__timeFilter(access_at)\nGROUP BY time, browser\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "[DBLog]ページごとのアクセス",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(access_at,1h,0),\n  access_page AS \"access_page\",\n  count(access_page) AS \"access_page\"\nFROM access_logs\nWHERE\n  $__timeFilter(access_at)\nGROUP BY 1, access_page\nORDER BY 1",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "[DBLog]国ごとのアクセス",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "rawSql": "SELECT\n  $__timeGroupAlias(access_at,1h,0),\n  iso_country_code AS metric,\n  count(id) AS \"id\"\nFROM access_logs\nWHERE\n  $__timeFilter(access_at)\nGROUP BY 1,2\nORDER BY 1,2",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}