apiVersion: v1
kind: Service
metadata:
  name: blue-green-app
  namespace: practice
  labels:
    app: blue-green-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: blue-green-app