apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      layer: app-node
  template:
    metadata:
      name: app-pod
      labels:
        layer: app-node
    spec:
      containers:
        - name: app-container
          image: localhost:5000/glory_of/k8s-hpa-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: "SPRING_REDIS_HOST"
              value: "redis-service"
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi