apiVersion: v1
kind: Service
metadata:
  name: practice-zipkin-service
  namespace: chaos-tracing
spec:
  type: NodePort
  selector:
    app: practice-zipkin
  ports:
    - name: zipkin-outer-port
      protocol: TCP
      port: 9411
      targetPort: zipkin-port
      nodePort: 30411