version: "3"
services:
  goods-app:
    build: goods-app
    container_name: goods-app
  keycloak:
    build: keycloak
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin-password
      - KEYCLOAK_IMPORT=/tmp/goods-realm.json
    ports:
      - 3000:8080

