version: "3"
services:
  dev-db:
    build: 
      context: ./db
      args:
        - profile=dev
    env_file:
      - common.env
      - common-db.env
    ports:
      - 54321:5432
    networks:
      - app-network
  dev-app:
    build:
      context: ./app-with-vault
      args:
        - profile=dev
        - mq_user=mq-user
        - mq_pass=mq-password
    depends_on:
      - config-server
      - dev-db
      - mq
    env_file:
      - common.env
    ports:
      - 8081:8080
    networks:
      - app-network
  static-app:
    build:
      context: ./app-static
      args:
        - profile=static
    depends_on:
      - config-server
    env_file:
      - common.env
    ports:
      - 8083:8080
    networks:
      - app-network
  stage-db:
    build:
      context: ./db
      args:
        - profile=stage
    env_file:
      - common.env
      - common-db.env
    ports:
      - 54322:5432
    networks:
      - app-network
  stage-app:
    build:
      context: ./app-with-vault
      args:
        - profile=stage
        - mq_user=mq-user
        - mq_pass=mq-password
    depends_on:
      - config-server
      - stage-db
      - mq
    env_file:
      - common.env
    ports:
      - 8082:8080
    networks:
      - app-network
  config-server:
    build:
      context: ./config-server
      args:
        - mq_user=mq-user
        - mq_pass=mq-password
    depends_on:
      - vault
      - mq
    env_file:
      - common.env
    ports:
      - 8888:8888
    networks:
      - app-network
  vault:
    build:
      context: ./vault
    env_file:
      - common.env
    ports:
      - 8200:8200
    networks:
      - app-network
  mq:
    build:
      context: ./mq
    env_file:
      - common.env
    environment:
      - RABBITMQ_DEFAULT_USER=mq-user
      - RABBITMQ_DEFAULT_PASS=mq-password
    ports:
      - 5672:5672
    networks:
      - app-network

networks:
  app-network:
