---
test_name: Success update user

includes:
  - !include ../component/auth_component.yaml
  - !include update_user_variables.yaml

stages:
  - type: ref
    id: create_csrf_token

  - type: ref
    id: create_auth_token

  - name: Update user
    request:
      url: "{target_url}/user/{update_target_user_id}"
      method: PUT
      headers:
        X-CSRF-TOKEN: "{csrf_token}"
        Authorization: "Bearer {auth_token}"
      json:
        givenName: "{given_name}"
        familyName: "{family_name}"
    response:
      status_code: 200
      json:
        userId: "{update_target_user_id}"

  - name: Get user
    request:
      url: "{target_url}/user/{update_target_user_id}"
      method: GET
      headers:
        X-CSRF-TOKEN: "{csrf_token}"
        Authorization: "Bearer {auth_token}"
    response:
      status_code: 200
      json:
        userId: "{update_target_user_id}"
        givenName: "{given_name}"
        familyName: "{family_name}"

---
test_name: Bad request

includes:
  - !include ../component/auth_component.yaml
  - !include update_user_variables.yaml

stages:
  - type: ref
    id: create_csrf_token

  - type: ref
    id: create_auth_token

  - name: update user
    request:
      url: "{target_url}/user/{update_target_user_id}"
      method: PUT
      headers:
        X-CSRF-TOKEN: "{csrf_token}"
        Authorization: "Bearer {auth_token}"
      json:
        givenName: ""
        familyName: "{family_name}"
    response:
      status_code: 400

