apiVersion: v1
kind: Service
metadata:
  name: practice-web-service
  namespace: chaos-app
spec:
  type: NodePort
  selector:
    app: practice-web
  ports:
    - name: web-outer-port
      protocol: TCP
      port: 80
      targetPort: web-port
      nodePort: 30080