apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
data:
  fluent.conf: |-
    <source>
      @type tail
      @id in_tail_app_log
      path "/var/log/containers/app-deployment-*.log"
      pos_file /var/log/app.log.pos
      tag app
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <source>
      @type tail
      @id in_tail_db_log
      path "/var/log/containers/db-deployment-*.log"
      pos_file /var/log/db.log.pos
      tag db
      read_from_head true
      <parse>
        @type json
      </parse>
    </source>

    <source>
      @type tail
      @id in_tail_web_log
      path "/var/log/containers/web-deployment-*.log"
      pos_file /var/log/web.log.pos
      tag web
      read_from_head true
      <parse>
        @type apache2
      </parse>
    </source>

    <match **>
      @type elasticsearch
      host elasticsearch
      port 9200
      logstash_format true
    </match>