apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-config
data:
  fluent.conf: |-
    <source>
      @type tail
      path "/var/log/containers/app-deployment-*.log"
      tag app
      read_from_head true
      <parse>
        @type json
        time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>

    <match **>
      @type file
      path /tmp/app-log
    </match>