apiVersion: v1
kind: Service
metadata:
  name: grafana-outer-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: grafana-outer-port
      protocol: TCP
      port: 3000
      targetPort: grafana-ui-port
      nodePort: 30000
    - name: loki-outer-port
      protocol: TCP
      port: 3100
      targetPort: loki-port
      nodePort: 30100
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-inner-service
spec:
  selector:
    app: grafana
  ports:
    - name: tempo-outer-port
      protocol: TCP
      port: 3200
      targetPort: tempo-port
    - name: tempo-tr-port
      protocol: TCP
      port: 14268
      targetPort: tempo-jg-port