apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - name: kafka-outer-port
      protocol: TCP
      port: 9092
      targetPort: kafka-port
      nodePort: 30092
    - name: zk-outer-port
      protocol: TCP
      port: 2181
      targetPort: zk-port
      nodePort: 30081