---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    layer: app-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    layer: db-node
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379