apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    layer: web-node
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: LoadBalancer
  selector:
    layer: app-node
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080


---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: LoadBalancer
  selector:
    layer: db-node
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379