apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: app-metrics
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['app-service:8080']
      - job_name: web-metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['web-service:9117']
      - job_name: redis-metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['redis-service:9121']