apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: app-metrics
        scrape_interval: 5s
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: app-service
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: 8080
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: ${1}:${2}
            target_label: __address__
          - source_labels:
            - __meta_kubernetes_service_name
            target_label: job
          - source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container_name
          - source_labels:
            - __meta_kubernetes_pod_uid
            target_label: container_id
      - job_name: web-metrics
        scrape_interval: 5s
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: web-service
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: 9117
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: ${1}:${2}
            target_label: __address__
          - source_labels:
            - __meta_kubernetes_service_name
            target_label: job
          - source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container_name
          - source_labels:
            - __meta_kubernetes_pod_uid
            target_label: container_id
      - job_name: db-metrics
        scrape_interval: 5s
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: redis-service
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: 9121
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: (.+):(?:\d+);(\d+)
            replacement: ${1}:${2}
            target_label: __address__
          - source_labels:
            - __meta_kubernetes_service_name
            target_label: job
          - source_labels:
            - __meta_kubernetes_pod_container_name
            target_label: container_name
          - source_labels:
            - __meta_kubernetes_pod_uid
            target_label: container_id