apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-config
data:
  prometheus.yml: |-
    scrape_configs:
      - job_name: app-metrics
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['app-service:8080']
