apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-deployment
spec:
  selector:
    matchLabels:
      layer: tracing-node
  template:
    metadata:
      name: tracing-pod
      labels:
        layer: tracing-node
    spec:
      containers:
        - name: tracing-container
          image: openzipkin/zipkin:2.22
          ports:
            - name: tracing-port
              containerPort: 9411