---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
spec:
  type: NodePort
  selector:
    layer: bff-node
  ports:
    - protocol: TCP
      port: 8000
      targetPort: bff-port
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-service
spec:
  type: NodePort
  selector:
    layer: tracing-node
  ports:
    - protocol: TCP
      port: 9411
      targetPort: tracing-port
      nodePort: 30090