---
apiVersion: v1
kind: Service
metadata:
  name: published-web-service
spec:
  type: NodePort
  selector:
    layer: web-node
  ports:
    - protocol: TCP
      port: 8000
      targetPort: web-port
      nodePort: 30080
