apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: practice
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 0
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80