apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: nginx