apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    events {}
    http {
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;
      upstream backend {
        server app-service:8080;
      }
      server {
        location /api {
          proxy_pass http://backend/api;
        }
      }
    }
