apiVersion: v1
kind: Service
metadata:
  name: pyroscope-service
spec:
  type: NodePort
  selector:
    app: pyroscope
  ports:
    - name: out-port
      protocol: TCP
      port: 4040
      targetPort: service-port
      nodePort: 30040