apiVersion: v1
kind: Service
metadata:
  name: flipt
spec:
  type: NodePort
  selector:
    app: flipt
  ports:
    - name: http-port
      protocol: TCP
      port: 8080
      targetPort: http-port
      nodePort: 30080
    - name: grpc-port
      protocol: TCP
      port: 9090
      targetPort: http-port
      nodePort: 30090