apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    load_module modules/ngx_http_opentracing_module.so;
    events {}

    http {
      opentracing_load_tracer /usr/local/lib/libzipkin_opentracing_plugin.so /etc/nginx-zipkin/nginx-zipkin.conf;
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      opentracing on;

      upstream backend {
        server app-service:8080;
      }

      server {

        location /api {
          opentracing_propagate_context;
          proxy_pass http://backend/api;
        }
      }
    }
  nginx-zipkin.conf: |-
    {
      "service_name": "front-web",
      "collector_host": "published-tracing-service",
      "collector_port": 9411
    }