apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |-
    load_module modules/ngx_http_opentracing_module.so;
    events {}

    http {
      opentracing_load_tracer /usr/local/lib/libzipkin_opentracing_plugin.so /etc/nginx-zipkin/nginx-zipkin.conf;
      resolver kube-dns.kube-system.svc.cluster.local valid=10s;

      opentracing on;
      include /etc/nginx/conf.d/nginx-env.conf;

      upstream backend {
        server app-service:8080;
      }

      server {

        location /api {
          proxy_pass http://backend/api;
          opentracing_propagate_context;
        }
      }
    }
  nginx-env.conf.template: |-
    opentracing_tag custom_k8s_nodeName ${CUSTOM_TRACE_NODENAME};
    opentracing_tag custom_k8s_nameSpace ${CUSTOM_TRACE_NAMESPACE};
    opentracing_tag custom_k8s_podName ${CUSTOM_TRACE_PODNAME};
    opentracing_tag custom_k8s_podIp ${CUSTOM_TRACE_PODIP};
  nginx-zipkin.conf: |-
    {
      "service_name": "front-web",
      "collector_host": "published-tracing-service",
      "collector_port": 9411
    }