apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      layer: web-node
  template:
    metadata:
      name: web-pod
      labels:
        layer: web-node
    spec:
      containers:
        - name: web-container
          image: localhost:5000/glory_of/k8s-tracing-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-core-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-zipkin-config
              mountPath: /etc/nginx-zipkin
      volumes:
        - name: nginx-core-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-zipkin-config
          configMap:
            name: nginx-config
            items:
              - key: nginx-zipkin.conf
                path: nginx-zipkin.conf