apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      layer: web-node
  template:
    metadata:
      name: web-pod
      labels:
        layer: web-node
    spec:
      containers:
        - name: web-container
          image: localhost:5000/glory_of/k8s-tracing-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: CUSTOM_TRACE_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CUSTOM_TRACE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CUSTOM_TRACE_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUSTOM_TRACE_PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          volumeMounts:
            - name: nginx-core-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-config-template
              mountPath: /etc/nginx/templates
            - name: nginx-zipkin-config
              mountPath: /etc/nginx-zipkin
      volumes:
        - name: nginx-core-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: nginx-config-template
          configMap:
            name: nginx-config
            items:
              - key: nginx-env.conf.template
                path: nginx-env.conf.template
        - name: nginx-zipkin-config
          configMap:
            name: nginx-config
            items:
              - key: nginx-zipkin.conf
                path: nginx-zipkin.conf