apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      layer: web-node
  template:
    metadata:
      name: web-pod
      labels:
        layer: web-node
    spec:
      containers:
        - name: web-container
          image: localhost:5000/glory_of/k8s-tracing-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: CUSTOM_TRACE_NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CUSTOM_TRACE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CUSTOM_TRACE_PODNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CUSTOM_TRACE_PODIP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BOOT_PORT
              value: "80"
            - name: TRACING_ENABLE
              value: "true"
            - name: TRACING_SERVIE_NAME
              value: "k8s-web"
            - name: TRACING_HOST
              value: "published-tracing-service"
            - name: TRACING_PORT
              value: "9411"
            - name: PROXY_HOST
              value: "http://app-service"
            - name: PROXY_PORT
              value: "8080"
