apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd
  labels:
    app: flagd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd
  template:
    metadata:
      labels:
        app: flagd
    spec:
      containers:
        - name: flagd
          image: ghcr.io/open-feature/flagd:v0.10.1
          ports:
            - name: listen-port
              containerPort: 8013
            - name: management-port
              containerPort: 8014
            - name: grpc-port
              containerPort: 8015
            - name: ofrep-port
              containerPort: 8016
          args:
            - "start"
            - "--debug"
            - "--uri"
            - "file:./etc/flagd/flag.json"
          volumeMounts:
            - name: flagd-config
              mountPath: /etc/flagd/flag.json
              subPath: flag.json
      volumes:
        - name: flagd-config
          configMap:
            name: flagd
            items:
              - key: flag.json
                path: flag.json
