apiVersion: v1
kind: Service
metadata:
  name: flagd
spec:
  type: NodePort
  selector:
    app: flagd
  ports:
    - protocol: TCP
      port: 8013
      targetPort: external-port
      nodePort: 30080