apiVersion: v1
kind: Service
metadata:
  name: flagd
spec:
  type: NodePort
  selector:
    app: flagd
  ports:
    - name: listen-port
      protocol: TCP
      port: 8013
      targetPort: listen-port
      nodePort: 30083
    - name: management-port
      protocol: TCP
      port: 8014
      targetPort: management-port
      nodePort: 30084
    - name: grpc-port
      protocol: TCP
      port: 8015
      targetPort: grpc-port
      nodePort: 30085
    - name: ofrep-port
      protocol: TCP
      port: 8016
      targetPort: ofrep-port
      nodePort: 30086