apiVersion: v1
kind: Service
metadata:
  name: grafana-outer-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - name: grafana-outer-port
      protocol: TCP
      port: 3000
      targetPort: grafana-ui-port
      nodePort: 30000