{
 "title": "APIサーバ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",job=\"api-server-metrics\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\",job=\"api-server-metrics\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Thread",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=\"api-server-metrics\"}",
     "legendFormat": "Live Thread"
    },
    {
     "expr": "jvm_threads_daemon_threads{job=\"api-server-metrics\"}",
     "legendFormat": "Deamon Threads"
    },
    {
     "expr": "tomcat_threads_current_threads{job=\"api-server-metrics\"}",
     "legendFormat": "Tomcat Current"
    },
    {
     "expr": "tomcat_threads_busy_threads{job=\"api-server-metrics\"}",
     "legendFormat": "Tomcat Busy"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(jvm_gc_pause_seconds_count{job=\"api-server-metrics\"}[30s])",
     "legendFormat": "{{cause}} Count"
    }
   ]
  },
  {
   "title": "CPU Usagae",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(irate(node_cpu_seconds_total{job=\"api-os-metrics\"}[5m]))",
     "legendFormat": "{{mode}}(CPU-{{cpu}})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"api-os-metrics\"}",
     "legendFormat": "1minute"
    },
    {
     "expr": "node_load5{job=\"api-os-metrics\"}",
     "legendFormat": "5minute"
    },
    {
     "expr": "node_load15{job=\"api-os-metrics\"}",
     "legendFormat": "15minute"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"api-os-metrics\",mountpoint=\"/etc/hosts\"}",
     "legendFormat": "Disk Space"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"api-os-metrics\", device=\"sda\"}[1m])",
     "legendFormat": "sda"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}