{
 "title": "Go-Frontサーバ",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=\"go-front-server-metrics\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_idle_bytes{job=\"go-front-server-metrics\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"go-front-server-metrics\"}",
     "legendFormat": "Inuse"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"go-front-server-metrics\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "GC",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(go_gc_duration_seconds_count{job=\"go-front-server-metrics\"}[30s])",
     "legendFormat": "Count"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "container_cpu_load_average_10s{name=\"mon-pro-go-front\"}",
     "legendFormat": "Load Average 10s"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_read_seconds_total{name=\"mon-pro-go-front\"}[1m])",
     "legendFormat": "Read"
    },
    {
     "expr": "irate(container_fs_write_seconds_total{name=\"mon-pro-go-front\"}[1m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_limit_bytes{name=\"mon-pro-go-front\"} - container_fs_usage_bytes{name=\"mon-pro-go-front\"}",
     "legendFormat": "Disk Space"
    }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_swap{name=\"mon-pro-go-front\"}",
     "legendFormat": "Swap"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"mon-pro-go-front\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "container_memory_rss{name=\"mon-pro-go-front\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "container_memory_cache{name=\"mon-pro-go-front\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "container_memory_mapped_file{name=\"mon-pro-go-front\"}",
     "legendFormat": "Mapped File"
    }
   ]
  }
 ]
}