{
 "title": "Webサーバ",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Access",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(apache_accesses_total[2m])",
     "legendFormat": "Count"
    },
    {
     "expr": "irate(http_request_duration_microseconds_sum{job=\"web-server-metrics\"}[2m])",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Worker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{job=\"web-server-metrics\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "CPU Usagae",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(irate(node_cpu_seconds_total{job=\"api-os-metrics\"}[5m]))",
     "legendFormat": "{{mode}}(CPU-{{cpu}})"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"web-os-metrics\"}",
     "legendFormat": "1minute"
    },
    {
     "expr": "node_load5{job=\"web-os-metrics\"}",
     "legendFormat": "5minute"
    },
    {
     "expr": "node_load15{job=\"api-os-metrics\"}",
     "legendFormat": "15minute"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"web-os-metrics\",mountpoint=\"/etc/hosts\"}",
     "legendFormat": "Disk Space"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{job=\"web-os-metrics\", device=\"sda\"}[2m])",
     "legendFormat": "sda"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_Buffers_bytes{job=\"web-os-metrics\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"web-os-metrics\"}",
     "legendFormat": "Available"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"web-os-metrics\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Memory Swap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes{job=\"web-os-metrics\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=\"web-os-metrics\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_SwapFree_bytes{job=\"api-os-metrics\"}",
     "legendFormat": "Free"
    }
   ]
  }
 ]
}