alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets:
        - mon-pro-alert:9093

rule_files:
  - "/etc/prometheus/alert-rule.yml"

scrape_configs:
  - job_name: api-server-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['mon-pro-app:8080']
  - job_name: api-os-metrics
    static_configs:
      - targets: ['mon-pro-app:9100']
  - job_name: db-server-metrics
    static_configs:
      - targets: ['mon-pro-db:9187']
  - job_name: db-os-metrics
    static_configs:
      - targets: ['mon-pro-db:9100']
  - job_name: web-server-metrics
    static_configs:
      - targets: ['mon-pro-web:9117']
  - job_name: web-os-metrics
    static_configs:
      - targets: ['mon-pro-web:9100']
  - job_name: service-metrics
    metrics_path: /probe
    params:
      module: [service]
    static_configs:
      - targets: ['http://mon-pro-web/users/limit']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: mon-pro-service:9115