scrape_configs:
  - job_name: api-web-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['mon-pro-app:8080']
  - job_name: api-os-metrics
    static_configs:
      - targets: ['mon-pro-app:9100']
  - job_name: db-metrics
    static_configs:
      - targets: ['mon-pro-db:9187']
  - job_name: db-os-metrics
    static_configs:
      - targets: ['mon-pro-db:9100']
  - job_name: web-server
    static_configs:
      - targets: ['mon-pro-web-exporter:9117']