apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.6
          ports:
            - name: zipkin-agent
              containerPort: 5775
            - name: jaeger-agent
              containerPort: 6831
            - name: jaeger-agent2
              containerPort: 6832
            - name: serve-configs
              containerPort: 5778
            - name: query-port
              containerPort: 16686
            - name: jaeger-col
              containerPort: 14268
            - name: zipkin-col
              containerPort: 9411