apiVersion: v1
kind: Service
metadata:
  name: jeager-service
spec:
  type: NodePort
  selector:
    app: jaeger
  ports:
    - name: ui
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 30080
    - name: collector
      protocol: TCP
      port: 14268
      targetPort: 30268