apiVersion: v1
kind: Service
metadata:
  name: kafka-ui-service
spec:
  type: NodePort
  selector:
    app: kafka-ui
  ports:
    - name: ui-outer-port
      protocol: TCP
      port: 8080
      targetPort: ui-port
      nodePort: 30080