keycloak:
  auth-server-url: http://localhost:3000/auth
  realm: goods-realm
  resource: goods-app
  base:
    uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${keycloak.base.uri}/token
            authorization-uri: ${keycloak.base.uri}/auth
            user-info-uri: ${keycloak.base.uri}/userinfo
            jwk-set-uri: ${keycloak.base.uri}/certs
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-name: goods-app
            client-id: goods-app
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-secret: e855901f-49cf-46a2-9026-372b2ebf9263
            scope: openid