apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: NodePort
  selector:
    app: influxdb
  ports:
    - name: app-outer-port
      protocol: TCP
      port: 8086
      targetPort: app-port
      nodePort: 30086