spring:
  main:
    banner-mode: off


management:
  metrics:
    tags:
      batch-name: "${BATCH_NAME:test}"
  prometheus:
    metrics:
      export:
        pushgateway:
          job: "test-runner"
          base-url: "http://localhost:30091"
          enabled: true
          shutdown-operation: push