type Mutation {
    updateUser(input: UserUpdateInput!): UserUpdatePayload!
    registerReview(input: RegisterReviewInput!): RegisterReviewPayload!
    updateReview(input: UpdateReviewInput!): UpdateReviewPayload
}