spring:
  profiles:
    active: native, vault

  cloud:
    config:
      server:
        vault:
          host: localhost
          port: 8200
          scheme: http
          connection-timeout: 10000
          read-timeout: 10000
          authentication: APPROLE
          backend: config
          kvVersion: 2
          app-role:
            role-id: test # ローカルの場合は固定のIDで設定した方がよさそう。
            secret-id: test # ローカルの場合は固定のIDで設定した方がよさそう。
            role: java-app
            app-role-path: approle
server:
  port: 8888