apiVersion: apps/v1
kind: Deployment
metadata:
  name: practice-app-deployment
  namespace: chaos-app
  labels:
    app: practice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: practice-app
  template:
    metadata:
      labels:
        app: practice-app
    spec:
      containers:
        - name: practice-app
          image: chaos-mesh-practice-app:0.0.1-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: app-port
          env:
            - name: SPRING_ZIPKIN_BASEURL
              value: "http://practice-zipkin-service.chaos-tracing:9411/"
            - name: SPRING_ZIPKIN_SERVICE_NAME
              value: "practice-app"
