apiVersion: v1
kind: Service
metadata:
  name: practice-app-service
spec:
  selector:
    app: practice-app
  ports:
    - name: app-outer-port
      protocol: TCP
      port: 8080
      targetPort: app-port