apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethink-db-deployment
  labels:
    app: rethink-db
spec:
  selector:
    matchLabels:
      app: rethink-db
  template:
    metadata:
      name: rethink-db
      labels:
        app: rethink-db
    spec:
      containers:
        - name: rethink-db-container
          image: rethinkdb:2.4.2-bullseye-slim
          ports:
            - containerPort: 28015
              name: db-port
            - containerPort: 8080
              name: admin-port