apiVersion: v1
kind: Service
metadata:
  name: rethink-db-service
spec:
  type: NodePort
  selector:
    app: rethink-db
  ports:
    - name: db-outer-port
      protocol: TCP
      port: 29015
      targetPort: db-port
      nodePort: 30015
    - name: admin-outer-port
      protocol: TCP
      port: 8080
      targetPort: admin-port
      nodePort: 30080