apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  application.yaml: |-
    spring:
      redis:
        sentinel:
          master: mymaster
          nodes: redis-service:26379
        lettuce:
          cluster:
            refresh:
              adaptive: true