apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
    - name: gateway-port
      protocol: TCP
      port: 9091
      targetPort: gateway-ui-port
      nodePort: 30091