spring:
  graphql:
    schema:
      file-extensions: .gql
  zipkin:
    base-url: "http://localhost:30080/"

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true

graphql:
  maxDepth: 5
  maxComplex: 30