spring:
  graphql:
    schema:
      file-extensions: .gql
    websocket:
      path: /graphql
  zipkin:
    base-url: "http://localhost:30080/"



management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,metrics,prometheus"
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    health:
      enabled: true

graphql:
  maxDepth: 15 # For IntrospectionQuery max depth value(Need 13)
  maxComplex: 60 # For IntrospectionQuery max complex value(Need 58)