apiVersion: v1
kind: Service
metadata:
  name: pyroscope
spec:
  type: NodePort
  selector:
    app: pyroscope
  ports:
    - name: app-outer-port
      protocol: TCP
      port: 4040
      targetPort: app-port
      nodePort: 30080