apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  selector:
    matchLabels:
      layer: web-node
  template:
    metadata:
      name: web-pod
      labels:
        layer: web-node
    spec:
      containers:
        - name: web-container
          image: localhost:5000/glory_of/k8s-metrics-web:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
        - name: exporter-container
          image: bitnami/apache-exporter:0.8.0
          # args: ["apache_exporter", "--scrape_uri='http://web-container/server-status/?auto'", "--insecure"]
          ports:
            - containerPort: 9117
