type Products {
    products: [Product!]!
}

type Product {
    id: String!
    code: String!
    name: String!
    members: [Member!]!,
    services: [Service!]!
}

type Member {
    id: String!
    givenName: String!
    familyName: String!
    birthDay: Date!
}

type Service {
    id: String!
    name: String!
    kind: ServiceKind!
}

enum ServiceKind {
    Finance
    Entertainment
    HealthCare
}