type Products {
    products: [Product!]!
}

type Product {
    id: String!
    code: String!
    name: String!
    members: [Member!]!,
    services: [Service!]!
}

type Member {
    id: String!
    givenName: String!
    familyName: String!
    birthDay: Date!
}

type Service {
    id: String!
    name: String!
    kind: ServiceKind!
}

enum ServiceKind {
    Finance
    Entertainment
    HealthCare
}

input RegisterProductInput {
    code: String!,
    name: String!,
    memberIDs: [String!]!,
    serviceIDs: [String!]!
}

type RegisterProductResult {
    id: String!
    product: Product!
}

input UpdateProductInput {
    id: String!,
    code: String!,
    name: String!,
    memberIDs: [String!]!,
    serviceIDs: [String!]!
}

type UpdateProductResult {
    id: String!
    product: Product!
}
