apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: practice-istio
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      layer: app-node
  template:
    metadata:
      namespace: practice-istio
      name: app-pod
      labels:
        layer: app-node
        app-num: one
    spec:
      containers:
        - name: app-container
          image: localhost:5000/glory_of/k8s-mesh-app:latest
          imagePullPolicy: Never
          ports:
            - name: app-port
              containerPort: 8080
          env:
            - name: SPRING_REDIS_HOST
              value: "redis-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: practice-istio
  name: app2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      layer: app-node
  template:
    metadata:
      namespace: practice-istio
      name: app-pod
      labels:
        layer: app-node
        app-num: two
    spec:
      containers:
        - name: app-container
          image: localhost:5000/glory_of/k8s-mesh-app:latest
          imagePullPolicy: Never
          ports:
            - name: app-port
              containerPort: 8080
          env:
            - name: SPRING_REDIS_HOST
              value: "redis-service"
