apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  clusterIP: None
  selector:
    layer: app-node
    app-num: one
  ports:
    - protocol: TCP
      port: 8080
      targetPort: app-port
---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  clusterIP: None
  selector:
    layer: app-node
    app-num: two
  ports:
    - protocol: TCP
      port: 8080
      targetPort: app-port