/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.2/samples
 */
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    id("java")
    kotlin("jvm") version "1.6.10"
}

group = "jp.glory"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_17

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    testImplementation("io.rest-assured:rest-assured:5.0.1")
    testImplementation("io.rest-assured:kotlin-extensions:5.0.1")
    testImplementation("io.rest-assured:spring-mock-mvc:5.0.1")
    testImplementation("io.rest-assured:json-path:5.0.1")
    testImplementation("io.rest-assured:xml-path:5.0.1")
    testImplementation(platform("org.junit:junit-bom:5.8.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.platform:junit-platform-suite-api")
    testImplementation("org.junit.platform:junit-platform-suite-engine")
    testImplementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2")
    testImplementation("com.fasterxml.jackson.core:jackson-databind:2.13.2.2")
    testImplementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.2")
}

tasks.withType<KotlinCompile> {
    kotlinOptions {
        freeCompilerArgs = listOf("-Xjsr305=strict")
        jvmTarget = "17"
    }
}

tasks.withType<Test> {
    useJUnitPlatform()
}