---
test_name: Get random seed

includes:
  - !include ../component/variables.yaml
  - !include ../component/auth_component.yaml

stages:
  - type: ref
    id: create_csrf_token

  - type: ref
    id: create_auth_token

  - name: Response is number
    request:
      url: "{target_url}/vulnerability/random-seed"
      method: GET
      headers:
        X-CSRF-TOKEN: "{csrf_token}"
        Authorization: "Bearer {auth_token}"
    response:
      status_code: 200
