apiVersion: v1
kind: Service
metadata:
  name: canary-app
  namespace: practice
  labels:
    app: canary-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 80
    nodePort: 30080
    protocol: TCP
  selector:
    app: canary-app