# logging.level.root: debug
logging:
  pattern:
    level: "%5p[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: "Spring Boot3 Practice"
  webflux:
    problemdetails:
      enabled: true

management:
  server:
    port: 8888
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:30411/api/v2/spans

