# logging.level.root: debug
spring:
  webflux:
    problemdetails:
      enabled: true

management:
  server:
    port: 8888
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health,prometheus"

  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true


