version: "3"
services:
  mon-pro-app:
    build: app
    container_name: mon-pro-app
    depends_on: 
      - mon-pro-db
    env_file:
      - ./common.env
    ports:
      - 8080:8080
      - 9117
    networks: 
      - pro-net
  mon-pro-db:
    build: db
    container_name: mon-pro-db
    environment:
      - LC_ALL=C.UTF-8
    env_file:
      - ./common.env
    volumes:
      - mon-db-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - pro-net
  mon-pro-db-exporter:
    build: db-exporter
    container_name: mon-pro-db-exporter
    depends_on: 
      - mon-pro-db
    environment:
      - DATA_SOURCE_NAME="postgresql://monitor-user:monitor-pass@mon-pro-db:5432/postgres?sslmode=disable"
    env_file:
      - ./common.env
    networks: 
      - pro-net
  mon-pro-web:
    build: web
    container_name: mon-pro-web
    env_file:
      - ./common.env
    ports:
      - 80:80
    networks: 
      - pro-net
  mon-pro-web-exporter:
    build: web-exporter
    container_name: mon-pro-web-exporter
    depends_on: 
      - mon-pro-web
    env_file:
      - ./common.env
    ports:
      - 9117:9117
    command: [ "apache_exporter", "--scrape_uri=http://mon-pro-web/server-status?auto"]
    networks: 
      - pro-net
  mon-prometheus:
    build: prometheus
    container_name: mon-prometheus
    env_file:
      - ./common.env
    volumes:
      - mon-pro-vol:/prometheus-data
    ports:
      - 9090:9090
    networks: 
      - pro-net 
  mon-grafana:
    build: grafana
    container_name: grafana
    depends_on: 
      - mon-pro-db
    env_file:
      - ./common.env
    environment:
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
    ports: 
      - 3000:3000
    networks: 
      - pro-net


volumes:
  mon-db-vol:
    driver: local
  mon-pro-vol:
    driver: local

networks:
  pro-net:
