apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  selector:
    matchLabels:
      layer: db-node
  template:
    metadata:
      name: db-pod
      labels:
        layer: db-node
    spec:
      containers:
        - name: db-container
          image: redis:5.0.9
          ports:
            - containerPort: 6379
        - name: exporter-container
          image: bitnami/redis-exporter:1.9.0
          ports:
             - containerPort: 9121

