apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    layer: db-node
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
    - name: metrics
      protocol: TCP
      port: 9121
      targetPort: 9121